# stage1 as builder
FROM node as builder

WORKDIR /vue-ui

# Copy the package.jso
COPY package*.json ./

# Copy rest of the files
COPY . .

# Build the project
RUN npm install
RUN npm run build


FROM nginx:alpine as production-build
# Copy from the stahg 1
COPY --from=builder /vue-ui/dist /usr/share/nginx/html
COPY ./nginx.config /etc/nginx/conf.d/default.conf

EXPOSE 10006
ENTRYPOINT ["nginx", "-g", "daemon off;"]