FROM python:3

ADD . /code

WORKDIR /code

RUN pip install --upgrade pip setuptools
RUN pip install -r requirements.in
RUN python setup.py develop
RUN python setup.py install

CMD [ "pserve", "production.ini" ]