services:
  db:
    container_name: hapi-db
    image: mysql:5.7
    restart: always
    env_file:
      - ./prod.env
    volumes:
      - ${DB_PATH}:/var/lib/mysql

  backend:
    image: hapi-backend
    container_name: hapi-backend
    env_file:
      - ./prod.env
    environment:
      - MYSQL_HOST=hapi-db
    build: 
      context: .
      dockerfile: ./Dockerfile.prod
    ports:
      - 6543:6543
    volumes:
      - ./prod.log:/code/prod.log
    links:
      - db
